// Generated by CoffeeScript 2.5.1
// markdownify.coffee
var disabled;

import {
  strict as assert
} from 'assert';

import marked from 'marked';

import {
  config
} from '../starbucks.config.js';

import {
  say,
  undef
} from '@jdeighan/coffee-utils';

import {
  slurp
} from '@jdeighan/coffee-utils/fs';

import {
  undentedBlock
} from '@jdeighan/coffee-utils/indent';

import {
  procContent
} from './StringInput.js';

disabled = false;

export var disableMarkdown = function() {
  return disabled = true;
};

export var enableMarkdown = function() {
  return disabled = false;
};

// ---------------------------------------------------------------------------
export var markdownify = function(text) {
  var html;
  if (disabled) {
    return text;
  }
  html = marked(undentedBlock(text), {
    grm: true,
    headerIds: false
  });
  return html;
};

// ---------------------------------------------------------------------------
export var markdownifyFile = function(filename) {
  var fpath, html, text;
  fpath = `${config.markdownDir}/${filename}`;
  text = slurp(fpath);
  html = markdownify(text);
  return html;
};
