// Generated by CoffeeScript 2.7.0
// pannable.coffee
export var pannable = function(node) {
  var handleMousedown, handleMousemove, handleMouseup, x, y;
  x = y = 0;
  handleMousedown = function(event) {
    x = event.clientX;
    y = event.clientY;
    node.dispatchEvent(new CustomEvent('panstart', {
      detail: {x, y}
    }));
    window.addEventListener('mousemove', handleMousemove);
    return window.addEventListener('mouseup', handleMouseup);
  };
  handleMousemove = function(event) {
    var dx, dy;
    dx = event.clientX - x;
    dy = event.clientY - y;
    x = event.clientX;
    y = event.clientY;
    return node.dispatchEvent(new CustomEvent('panmove', {
      detail: {x, y, dx, dy}
    }));
  };
  handleMouseup = function(event) {
    x = event.clientX;
    y = event.clientY;
    node.dispatchEvent(new CustomEvent('panend', {
      detail: {x, y}
    }));
    window.removeEventListener('mousemove', handleMousemove);
    return window.removeEventListener('mouseup', handleMouseup);
  };
  node.addEventListener('mousedown', handleMousedown);
  return {
    destroy: function() {
      return node.removeEventListener('mousedown', handleMousedown);
    }
  };
};
