// Generated by CoffeeScript 2.5.1
// sassify.coffee
var SassMapper, disabled;

import sass from 'sass';

import {
  say,
  undef
} from '@jdeighan/coffee-utils';

import {
  procContent
} from '@jdeighan/string-input';

disabled = false;

// ---------------------------------------------------------------------------
export var disableSassify = function() {
  return disabled = true;
};

// ---------------------------------------------------------------------------
SassMapper = function(line, oInput) {
  if (line.match(/^\s*$/) || line.match(/^\s*#\s/)) {
    return undef;
  }
  return line;
};

// ---------------------------------------------------------------------------
export var sassify = function(text) {
  var mapped, result;
  mapped = procContent(text, SassMapper);
  if (disabled) {
    return mapped;
  }
  result = sass.renderSync({
    data: mapped,
    indentedSyntax: true,
    indentType: "tab"
  });
  return result.css.toString();
};
